---
- name: install dependencies
  yum: pkg={{ item }} state=installed
  loop:
    - golang
    - git

- name: install supervisord
  include_role:
    name: geerlingguy.supervisor
  when: supervisor_install
