---
# handlers file for prom-haproxy-exporter
- name: add haproxy_exporter
  supervisorctl:
    name: haproxy_exporter
    state: present
  become: true

- name: restart haproxy_exporter
  supervisorctl:
    name: haproxy_exporter
    state: restarted
  become: true

- name: check exporter port
  wait_for:
    host: "{{ haproxy_exporter_ip }}"
    port: "{{ haproxy_exporter_port }}"
